export const LOADING_CHARACTERS = "[CHARACTERS] LOADING CHARACTERS";
export const GET_COMICS_BY_CHARACTER = "[CHARACTERS] GET COMICS BY CHARACTER";
export const GET_STORIES_BY_CHARACTER = "[CHARACTERS] GET STORIES BY CHARACTER";
export const GET_CHARACTERS = "[CHARACTERS] GET CHARACTERS";
export const GET_CHARACTER_BY_ID = "[CHARACTERS] GET CHARACTER BY ID";
export const GET_ERRORS = "[CHARACTERS] GET ERRORS";
