export const LOADING_COMICS = "[COMICS] LOADING COMICS";
export const GET_COMICS = "[COMICS] GET COMICS";
export const GET_COMIC_BY_ID = "[COMICS] GET COMIC BY ID";
export const GET_CHARACTERS_BY_COMIC = "[COMICS] GET CHARACTERS BY COMIC";
export const GET_STORIES_BY_COMIC = "[COMICS] GET STORIES BY COMIC";
export const GET_ERRORS = "[COMICS] GET ERRORS";
