export const LOADING_STORIES = "[STORIES] LOADING STORIES";
export const GET_STORIES = "[STORIES] GET STORIES";
export const GET_STORY_BY_ID = "[STORIES] GET STORY BY ID";
export const GET_CHARACTERS_BY_STORY = "[STORIES] GET CHARACTERS BY STORY";
export const GET_COMICS_BY_STORY = "[STORIES] GET STORIES BY STORY";
export const GET_ERRORS = "[STORIES] GET ERRORS";
